#!/usr/bin/env php
<?php declare(strict_types=1);

use Tristan\Icy\Cli\RunDepMap;
use Symfony\Component\Console\Application;

require_once(__DIR__ . "/src/DepMap.php");

if (isset($GLOBALS['_composer_autoload_path'])) {
    define('ICY_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);

    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
        if (file_exists($file)) {
            define('ICY_COMPOSER_INSTALL', $file);

            break;
        }
    }

    unset($file);
}


const VERSION = "v0.0.1";

if (php_sapi_name() === "cli") {
    // https://symfony.com/doc/current/console.html#configuring-the-command
    $application = new Application();
    $application->setName("Icy");
    $application->setVersion(VERSION);
    $application->add(new RunDepMap());


    try {
        $application->run();
    } catch (Exception $e) {
        echo $e->getMessage() . PHP_EOL;
    }
}

