#!/usr/bin/env php
<?php declare(strict_types=1);

use Tristan\Icy\Cli\RunDepMap;
use Symfony\Component\Console\Application;


if (isset($GLOBALS['_composer_autoload_path'])) {
    define('ICY_COMPOSER_INSTALL', $GLOBALS['_composer_autoload_path']);

    unset($GLOBALS['_composer_autoload_path']);
} else {
    foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php', $_ENV["HOME"] . "/.config/composer/vendor/autoload.php", $_ENV["HOME"] . "/.composer/vendor/autoload.php") as $file) {
        if (file_exists($file)) {
            define('ICY_COMPOSER_INSTALL', $file);

            break;
        }
    }

    unset($file);
}

if (!defined('ICY_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );

    die(1);
}

require_once ICY_COMPOSER_INSTALL;

const VERSION = "v0.0.1";

if (php_sapi_name() === "cli") {
    // https://symfony.com/doc/current/console.html#configuring-the-command
    $application = new Application();
    $application->setName("Icy");
    $application->setVersion(VERSION);
    $application->add(new RunDepMap());


    try {
        $application->run();
    } catch (Exception $e) {
        echo $e->getMessage() . PHP_EOL;
    }
}

